apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  labels:
    project: roboshop
    component: catalogue
    tier: app-tier

data:
  MONGO: "true" 
  MONGO_URL: "mongodb://mongodb:27017/catalogue"