---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: app-tier
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: app-tier
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port